defmodule JobProcessorWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :job_processor

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :job_processor,
    gzip: not code_reloading?,
    only: JobProcessorWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug :assume_json_body

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug JobProcessorWeb.Router

  # The API only takes JSON bodies, but `curl -d` without a content-type header sends them as
  # application/x-www-form-urlencoded, and some clients send no content type at all. Parse
  # both as JSON instead of answering "tasks can't be blank".
  defp assume_json_body(%{method: "POST"} = conn, _opts) do
    case get_req_header(conn, "content-type") do
      [] ->
        put_req_header(conn, "content-type", "application/json")

      ["application/x-www-form-urlencoded" <> _] ->
        put_req_header(conn, "content-type", "application/json")

      _ ->
        conn
    end
  end

  defp assume_json_body(conn, _opts), do: conn
end
